[package]
name = "sunholo/motoko_ext_context_mode"
version = "0.1.0"
edition = "1"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[effects]
max = ["Process", "FS", "Env", "SharedMem"]

[exports]
modules = ["sunholo/motoko_ext_context_mode/register"]
